djangotodo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
]

todo/urls.py
from django.urls import path
from .views import (
    TodoListView,
    TodoCreateView,
    TodoUpdateView,
    TodoDeleteView,
    TodoDetailView
)

app_name = 'todo'
urlpatterns = [
    path('', TodoListView.as_view(), name='list'),
    path('create', TodoCreateView.as_view(), name='create'),
    path('update/<int:pk>', TodoUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', TodoDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>', TodoDetailView.as_view(), name='detail'),
]

todo/models.py
from django.db import models
from django.utils import timezone


class Todo(models.Model):
    title = models.CharField(max_length=100)
    finish = models.BooleanField(default=False)
    created = models.DateField(default=timezone.now)

todo/forms.py
from django import forms
from .models import Todo


class TodoModelForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ('title', 'finish')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '待辦事項'})
        }

todo/views.py
from django.shortcuts import render
from .models import Todo
from .forms import TodoModelForm
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    DetailView
)


class TodoListView(ListView):
    model = Todo
    queryset = Todo.objects.filter(finish=False)  # 指定查詢條件
    template_name = 'todo/todo_list.html'  # 樣板路徑

    # 要傳遞的資料
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = TodoModelForm()  # 資料模型表單
        return context


class TodoCreateView(CreateView):
    model = Todo
    form_class = TodoModelForm  # 使用的表單類別
    success_url = '/todo'  # 儲存成功後要導向的網址


class TodoUpdateView(UpdateView):
    model = Todo
    form_class = TodoModelForm  # 使用的表單類別
    template_name = 'todo/todo_update.html'  # 修改樣板
    success_url = '/todo'  # 儲存成功後要導向的網址


class TodoDeleteView(DeleteView):
    model = Todo
    template_name = 'todo/todo_delete.html'  # 刪除樣板
    success_url = '/todo'  # 刪除成功後要導向的網址


class TodoDetailView(DetailView):
    model = Todo
    template_name = 'todo/todo_detail.html'

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>To Do List</title>
  </head>
  <body>

    <div class="container">
        <h1>To Do List</h1>
        <br />

        {% block content %}
        {% endblock  %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

todo/templates/todo/todo_delete.html
{% extends 'base.html' %}

{% block content %}

    是否確定刪除{{ object.title }}?
    <br />
    <br />
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="確定" />
        <a href="{% url 'todo:list' %}" class="btn btn-warning">取消</a>
    </form>

{% endblock  %}

todo/templates/todo/todo_detail.html
{% extends 'base.html' %}

{% block content %}

    <ul class="list-group list-group-flush">
        <li class="list-group-item">標題：{{ object.title }}</li>
        <li class="list-group-item">是否完成：{{ object.finish }}</li>
        <li class="list-group-item">建立日期：{{ object.created|date:'Y/m/d' }}</li>
    </ul>

{% endblock  %}

todo/templates/todo/todo_list.html
{% extends 'base.html' %}

{% block content %}

<form action="/todo/create" method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col">
            {{ form.title }}
        </div>
        <div class="col">
            <input type="submit" class="btn btn-primary" value="儲存">
        </div>
    </div>
</form>
<br />
<table class="table">
    <thead>
        <tr>
            <th>待辦事項</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for todo in object_list %}
        <tr>
            <td>{{ todo.title }}</td>
            <td style="text-align:right;">
                <a href="{% url 'todo:update' todo.id %}" class="btn btn-success">修改</a>
                <a href="{% url 'todo:delete' todo.id %}" class="btn btn-danger">刪除</a>
                <a href="{% url 'todo:detail' todo.id %}" class="btn btn-info">明細</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock  %}

todo/templates/todo/todo_update.html
{% extends 'base.html' %}

{% block content %}

    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label>待辦事項</label>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label class="form-check-label">是否完成</label>
            {{ form.finish }}
        </div>
        <input type="submit" class="btn btn-primary" value="儲存" />
    </form>

{% endblock  %}